version: '3'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: python_task
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    restart: always
    volumes:
      - .:/home/python/app
      - python-app:/home/python/app
    depends_on:
      - postgres
    stdin_open: true
    tty: true

volumes:
  postgres:
  python-app: